/**
 * Image optimization workflow for Basement Pickups.
 *
 * For every raster image in the configured source directories this script
 * generates responsive AVIF and WebP derivatives alongside the original
 * (the original is never modified or removed — it stays as the ultimate
 * <img> fallback and the re-encode source of truth). It then writes a typed
 * manifest the design-system <Image> atom reads to emit <picture> markup.
 *
 * The run is idempotent: a derivative is only re-encoded when it is missing or
 * older than its source, so adding one new image only processes that image.
 *
 * Usage:  pnpm run optimize:images
 *
 * See docs/ai/skills/optimize-images.md for the full contract.
 */

import { existsSync } from 'node:fs';
import { mkdir, readdir, stat, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import sharp from 'sharp';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const PUBLIC_DIR = path.join(ROOT, 'public');
const MANIFEST_PATH = path.join(ROOT, 'src/assets/imageManifest.ts');

/** Directories (relative to /public) whose raster images get optimized. */
const SOURCE_DIRS = ['assets/images/product-photos', 'assets/images/spirit-photos'];

/**
 * Responsive width ladder. A source is never upscaled: only widths smaller than
 * the source are emitted, plus the source's own width so full resolution is
 * always covered.
 */
const WIDTH_LADDER = [480, 768, 1200, 1600];

const SOURCE_EXTENSIONS = new Set(['.png', '.jpg', '.jpeg']);

const AVIF_OPTIONS = { quality: 50, effort: 4 };
const WEBP_OPTIONS = { quality: 74, effort: 4 };

/** Map an absolute file path under /public to its served URL path. */
function toUrlPath(absPath) {
  return '/' + path.relative(PUBLIC_DIR, absPath).split(path.sep).join('/');
}

/** Non-upscaling width set for a given source width, ascending. */
function targetWidthsFor(sourceWidth) {
  const widths = WIDTH_LADDER.filter((width) => width < sourceWidth);
  widths.push(sourceWidth);
  return [...new Set(widths)].sort((a, b) => a - b);
}

/** A derivative is stale when it does not exist or predates its source. */
async function isStale(outputPath, sourceMtimeMs) {
  if (!existsSync(outputPath)) return true;
  const outputStat = await stat(outputPath);
  return outputStat.mtimeMs < sourceMtimeMs;
}

async function encodeVariant(absSource, absOutput, width, format, options, sourceMtimeMs) {
  if (!(await isStale(absOutput, sourceMtimeMs))) return false;
  await sharp(absSource)
    .resize({ width, withoutEnlargement: true })
    [format](options)
    .toFile(absOutput);
  return true;
}

function serializeManifest(entries) {
  const lines = [
    '// GENERATED by scripts/optimize-images.mjs — do not edit by hand.',
    '// Run `pnpm run optimize:images` to regenerate.',
    '',
    "import type { ImageManifest } from './imageManifest.types';",
    '',
    'export const imageManifest: ImageManifest = {',
  ];

  for (const key of Object.keys(entries).sort()) {
    const entry = entries[key];
    lines.push(`  '${key}': {`);
    lines.push(`    width: ${entry.width},`);
    lines.push(`    height: ${entry.height},`);
    for (const format of ['avif', 'webp']) {
      lines.push(`    ${format}: [`);
      for (const variant of entry[format]) {
        lines.push(`      { width: ${variant.width}, src: '${variant.src}' },`);
      }
      lines.push('    ],');
    }
    lines.push('  },');
  }

  lines.push('};', '');
  return lines.join('\n');
}

async function main() {
  const entries = {};
  let encoded = 0;
  let upToDate = 0;

  for (const dir of SOURCE_DIRS) {
    const absDir = path.join(PUBLIC_DIR, dir);
    if (!existsSync(absDir)) continue;

    const files = (await readdir(absDir)).sort();
    for (const file of files) {
      const ext = path.extname(file).toLowerCase();
      if (!SOURCE_EXTENSIONS.has(ext)) continue;

      const absSource = path.join(absDir, file);
      const base = path.basename(file, ext);
      const { mtimeMs } = await stat(absSource);
      const metadata = await sharp(absSource).metadata();

      if (!metadata.width || !metadata.height) {
        console.warn(`  ! skipped (no dimensions): ${toUrlPath(absSource)}`);
        continue;
      }

      const avif = [];
      const webp = [];

      for (const width of targetWidthsFor(metadata.width)) {
        const avifOut = path.join(absDir, `${base}-${width}.avif`);
        if (await encodeVariant(absSource, avifOut, width, 'avif', AVIF_OPTIONS, mtimeMs))
          encoded += 1;
        else upToDate += 1;
        avif.push({ width, src: toUrlPath(avifOut) });

        const webpOut = path.join(absDir, `${base}-${width}.webp`);
        if (await encodeVariant(absSource, webpOut, width, 'webp', WEBP_OPTIONS, mtimeMs))
          encoded += 1;
        else upToDate += 1;
        webp.push({ width, src: toUrlPath(webpOut) });
      }

      entries[toUrlPath(absSource)] = {
        width: metadata.width,
        height: metadata.height,
        avif,
        webp,
      };
    }
  }

  await mkdir(path.dirname(MANIFEST_PATH), { recursive: true });
  await writeFile(MANIFEST_PATH, serializeManifest(entries), 'utf8');

  console.log(`Optimized images: ${encoded} encoded, ${upToDate} up-to-date.`);
  console.log(
    `Manifest: ${path.relative(ROOT, MANIFEST_PATH)} (${Object.keys(entries).length} originals).`,
  );
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
